# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aD rR rW
.outputs aR aW rD
.graph
aD+ aW+
aD- aW-
aR+ rR-
aR- scaled0
aW+ rW-
aW- p0
rD+ aD+
rD- aD-
rR+ aR+
rR- aR-
rW+ rD+
rW- rD-
p0 rW+
scaled0 rR+
.marking {p0 scaled0}
.end
