# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aO aX rI
.outputs aI rO rY
.graph
aI+ rI-
aI- unique0
aO+ rO- unique2 unique3
aO- unique4
aX+ rO+
aX- unique5
rI+ aI+ rY+
rI- aI-
rO+ aO+
rO- aO-
rY+ rY- unique1
rY- unique6
unique0 rI+
unique1 aX+
unique2 rY-
unique3 aI+
unique4 aI-
unique5 aI-
unique6 aX-
.marking {unique0}
.end
