# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aO rI
.outputs aI rO
.graph
aI+ rI-
aI- p0
aO+ rO-
aO- scaled1
rI+ scaled0
rI- aI-
rO+ aO+
rO- aO-
p0 rI+
scaled0 rO+
scaled1 aI+
.marking {p0}
.end
