# STG file generated by WorkOraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aO aI rA
.outputs aA rO rI
.graph
aA+ rA-
aA- p0
aO+ aA+
aO- aA-
aI+ rO+
aI- rO-
rA+ rI+
rA- rI-
rO+ aO+
rO- aO-
rI+ aI+
rI- aI-
p0 rA+
.marking {p0}
.end
