# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aO aO_L_ rI
.outputs aI cO rO rO_L_
.graph
aI+ rI-
aI- p0
aO+ cO+
aO- seqEnd0
aO_L_+ aI+
aO_L_- aI-
cO+ rO-
cO- seqEnd1
rI+ seqStart0
rI- seqStart1
rO+ aO+
rO- aO-
rO_L_+ aO_L_+
rO_L_- aO_L_-
p0 rI+
seqEnd0 rO_L_+
seqEnd1 rO_L_-
seqStart0 rO+
seqStart1 cO-
.marking {p0}
.end
