# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aD aI rO
.outputs aO rD rI
.graph
aD+ aO+
aD- aO-
aI+ rD+
aI- rD-
aO+ rO-
aO- p0
rD+ aD+
rD- aD-
rI+ aI+
rI- aI-
rO+ rI+
rO- rI-
p0 rO+
.marking {p0}
.end
