# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aF aG aO aT rA
.outputs aA rD rG rO
.graph
aA+ rA-
aA- p0
aF+ aA+
aF- aA-
aG+ rD+
aG- rD-
aO+ rO-
aO- p1
aT+ aT- p3
aT- rO+
rA+ p1
rA- aF- p3
rD+ p2
rD- p4
rG+ aG+
rG- aG-
rO+ aO+
rO- aO-
p0 rA+
p1 rG+
p2 aF+ aT+
p3 rG-
p4 aF- aT-
.marking {p0}
.end
