# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aD aE aO rI
.outputs aI rC rO
.graph
aD+ rO+
aD- rO-
aE+ aE- unique1
aE- unique3
aI+ rI-
aI- p0
aO+ aD- unique1
aO- unique3
rC+ unique0
rC- unique2
rI+ rC+
rI- rC-
rO+ aO+
rO- aO-
p0 rI+
unique0 aD+ aE+
unique1 aI+
unique2 aD- aE-
unique3 aI-
.marking {p0}
.end
