# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aA aB aD rO
.outputs aO rA rB rD
.graph
aA+ rD+
aA- rD-
aB+ rD+
aB- rD-
aD+ aO+
aD- aO-/1
aO+ rO-
aO-/1 p0
rA+ aA+
rA- aA-
rB+ aB+
rB- aB-
rD+ aD+
rD- aD-
rO+ rA+ rB+
rO- rA- rB-
p0 rO+
.marking {p0}
.end
