# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aX rI rO
.outputs aI aO rD rY
.graph
aI+ rI-
aI- unique0
aO+ rO-
aO- scaled0
aX+ aI+ scaled2
aX- aI- scaled4
rD+ rY+
rD- rY-
rI+ rY+
rI- rY-
rO+ scaled1
rO- scaled3
rY+ aX+
rY- aX-
scaled0 rO+
scaled1 rD+
scaled2 aO+
scaled3 rD-
scaled4 aO-
unique0 rI+
.marking {scaled0 unique0}
.end
