# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aI rO
.outputs aO rI
.graph
aI+ scaled1
aI- scaled3
aO+ rO-
aO- unqiue0
rI+ aI+
rI- aI-
rO+ scaled0
rO- scaled2
scaled0 rI+
scaled1 aO+
scaled2 rI-
scaled3 aO-
unqiue0 rO+
.marking {unqiue0}
.end
