# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aI aO rA
.outputs aA rI rO
.graph
aA+ rA-
aA- p0
aI+ rO+
aI- rO-
aO+ aA+
aO- aA-
rA+ rI+
rA- rI-
rI+ aI+
rI- aI-
rO+ aO+
rO- aO-
p0 rA+
.marking {p0}
.end
