# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aO rI
.outputs aI rO
.graph
aI+ rI-
aI- unique0
aO+ unique2
aO- unique4
rI+ unique1
rI- unique3
rO+ aO+
rO- aO-
unique0 rI+
unique1 rO+
unique2 aI+
unique3 rO-
unique4 aI-
.marking {unique0}
.end
