# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.1
.model Untitled
.inputs aO rI
.outputs aI rO
.graph
aI+ rI-
aI- scaled0
aO+ scaled2
aO- scaled4
rI+ scaled1
rI- scaled3
rO+ aO+
rO- aO-
scaled0 rI+
scaled1 rO+
scaled2 aI+
scaled3 rO-
scaled4 aI-
.marking {scaled0}
.end
