# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aE rI rO
.outputs aI aO rE
.graph
aE+ aI+ scaled2
aE- aI- scaled4
aI+ rI-
aI- unique0
aO+ rO-
aO- scaled0
rE+ aE+
rE- aE-
rI+ rE+
rI- rE-
rO+ scaled1
rO- scaled3
scaled0 rO+
scaled1 rE+
scaled2 aO+
scaled3 rE-
scaled4 aO-
unique0 rI+
.marking {scaled0 unique0}
.end
