# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aO0 rA
.outputs aA rO0
.internal cO
.graph
aA+ rA-
aA- unique0
aO0+ cO+
aO0- cO-
cO+ rO0- scaled1
cO- scaled3
rA+ scaled0
rA- scaled2
rO0+ aO0+
rO0- aO0-
scaled0 rO0+
scaled1 aA+
scaled2 cO-
scaled3 aA-
unique0 rA+
.marking {unique0}
.end
