# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aS rR rW
.outputs aR aW rS
.internal cS
.graph
aR+ rR-
aR- scaled0
aS+ aW+ cS+
aS- cS-
aW+ rW-
aW- unique0
cS+ rS-
cS- aW-
rR+ aR+
rR- aR-
rS+ scaled0
rS- aS-
rW+ rS+
rW- cS-
scaled0 aS+ rR+
unique0 rW+
.marking {unique0}
.end
