# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aO rI
.outputs aI rO
.graph
aI+/1 rI-/1
aI-/1 unqiue0
aO+ scaled1
aO- scaled3
rI+/1 scaled0
rI-/1 scaled2
rO+ aO+
rO- aO-
scaled0 rO+
scaled1 aI+/1
scaled2 rO-
scaled3 aI-/1
unqiue0 rI+/1
.marking {unqiue0}
.end
