# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aO rA
.outputs aA rO
.internal cO
.graph
aA+ rA-
aA- unique0
aO+ cO+
aO- cO-
cO+ rO- scaled1
cO- scaled3
rA+ scaled0
rA- scaled2
rO+ aO+
rO- aO-
scaled0 rO+
scaled1 aA+
scaled2 cO-
scaled3 aA-
unique0 rA+
.marking {unique0}
.end
