# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aL aM rO
.outputs aO rL rM
.graph
aL+ aO+
aL- aO-
aM+ aO+
aM- aO-
aO+ rO-
aO- p0
rL+ aL+
rL- aL-
rM+ aM+
rM- aM-
rO+ rL+ rM+
rO- rL- rM-
p0 rO+
.marking {p0}
.end
