# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aO rI
.outputs aI rO
.internal cO
.graph
aI+ rI-
aI- p0
aO+ cO+
aO- cO-
cO+ aI+ rO-
cO- aI-
rI+ rO+
rI- cO-
rO+ aO+
rO- aO-
p0 rI+
.marking {p0}
.end
