# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aO aX rI
.outputs aI rO rY
.graph
aI+ rI-
aI- unique0
aO+ unique2
aO- unique4
aX+ rO+
aX- unique6
rI+ rY+
rI- rY- unique3
rO+ aO+
rO- aO-
rY+ aI+ unique1
rY- aI- unique5
unique0 rI+
unique1 aX+
unique2 aI+
unique3 rO-
unique4 rY-
unique5 aX-
unique6 aI-
.marking {unique0}
.end
