# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aO rA
.outputs aA rO
.graph
aA+ rA-
aA- p1
aO+ rO-
aO- p0
rA+ p0
rA- aA-
rO+ aO+
rO- aO-
p0 rO+
p1 rA+
p2 aA+
.marking {p1}
.end
