# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aO rA rI
.outputs aA aI rO
.graph
aA+ rA-
aA- unique1
aI+ rI-
aI- unique0
aO+ aI+ unique3
aO- aI- unique5
rA+ unique2
rA- unique4
rI+ rO+
rI- rO-
rO+ aO+
rO- aO-
unique0 rI+
unique1 rA+
unique2 rO+
unique3 aA+
unique4 rO-
unique5 aA-
.marking {unique0 unique1}
.end
