# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aI aX rO
.outputs aO rI rY
.graph
aI+ rY+
aI- rY-
aO+ rO-
aO- p0
aX+ aO+
aX- aO-
rI+ aI+
rI- aI-
rO+ rI+
rO- rI-
rY+ aX+
rY- aX-
p0 rO+
.marking {p0}
.end
