# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aC aD aE aF rA rB
.outputs aA aB rC rD rE rF
.graph
aA+ rA-
aA- p0
aB+ rB-
aB- p1
aC+ aA+
aC- aA- p3
aD+ aB+
aD- aB- p3
aE+ rC+
aE- rC- p2
aF+ rD+
aF- rD- p2
rA+ rE+
rA- rE-
rB+ rF+
rB- rF-
rC+ aC+
rC- aC-
rD+ aD+
rD- aD-
rE+ aE+
rE- aE-
rF+ aF+
rF- aF-
p0 rA+
p1 rB+
p2 aE+ aF+
p3 rC+ rD+
.marking {p0 p1 p2 p3}
.end
