# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aI rO
.outputs aO rI
.graph
aI+ aO+
aI- aO-
aO+ rO-
aO- p0
rI+ aI+
rI- aI-
rO+ rI+
rO- rI-
p0 rO+
.marking {p0}
.end
