# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aF aG aO aT rA
.outputs aA rD rG rO
.internal cO
.graph
aA+ rA-
aA- p1
aF+ aA+
aF- aA-
aG+ rD+
aG- rD-
aO+ cO-
aO- p0
aT+ cO+
aT- rO+
cO+ aT- p0a
cO- rO-
rA+ p0
rA- aF- p0a
rD+ p2
rD- p3
rG+ aG+
rG- aG-
rO+ aO+
rO- aO-
p0 rG+
p0a rG-
p1 rA+
p2 aF+ aT+
p3 aF- aT-
.marking {p1}
.end
