# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aS aW rA rR
.outputs aA aR rS rW
.internal cS
.graph
aA+ rA-
aA- unique0
aR+ rR-
aR- scaled0 scaled1
aS+ aA+ cS+
aS- cS-
aW+ aA+ scaled1
aW- cS-
cS+ rS-
cS- aA-
rA+ rS+ rW+
rA- rW-
rR+ aR+
rR- aR-
rS+ scaled0
rS- aS-
rW+ aW+
rW- aW-
scaled0 aS+ rR+
scaled1 aR+ aS+
unique0 rA+
.marking {unique0}
.end
