# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aO rI
.outputs aI rO
.graph
aI+ rI-
aI- unique0
aO+ scaled1
aO- scaled3
rI+ scaled4
rI- scaled2
rO+ scaled5
rO- aO-
scaled0 aO+
scaled1 aI+
scaled2 rO-
scaled3 aI-
scaled4 rO+
scaled5
unique0 rI+
.marking {unique0}
.end
