# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs aD rR rW
.outputs aR aW rD
.graph
aD+ aW+
aD- aW-
aR+ rR-
aR- scaled0
aW+ rW-
aW- unique0
rD+ aD+
rD- aD-
rR+ aR+
rR- aR-
rW+ rD+
rW- rD-
scaled0 rR+
unique0 rW+
.marking {scaled0 unique0}
.end
